package net.ceoofgoogle.createclothes.init;

import net.ceoofgoogle.createclothes.CreateClothes;
import net.ceoofgoogle.createclothes.item.*;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public class CreateClothesModItems {
    public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(CreateClothes.MOD_ID);

    public static final DeferredItem<Item> CROWN = REGISTRY.register("crown", () -> new CrownItem.Helmet());
    public static final DeferredItem<Item> BUCKET_HAT = REGISTRY.register("bucket_hat", () -> new BucketHatItem.Helmet());
    public static final DeferredItem<Item> CAP = REGISTRY.register("cap", () -> new CapItem.Helmet());
    public static final DeferredItem<Item> OFFICER_CAP = REGISTRY.register("officer_cap", () -> new OfficerItem.Helmet());
    public static final DeferredItem<Item> OFFICER_TUNIC = REGISTRY.register("officer_tunic", () -> new OfficerItem.Chestplate());
    public static final DeferredItem<Item> TRICORN = REGISTRY.register("tricorn", () -> new TricornItem.Helmet());
    public static final DeferredItem<Item> REDCOAT = REGISTRY.register("redcoat", () -> new RedcoatItem.Chestplate());
    public static final DeferredItem<Item> BLACK_BOOTS = REGISTRY.register("black_boots", () -> new BlackBootsItem.Boots());
    public static final DeferredItem<Item> GRAY_BOOTS = REGISTRY.register("gray_boots", () -> new GrayBootsItem.Boots());
    public static final DeferredItem<Item> BROWN_BOOTS = REGISTRY.register("brown_boots", () -> new BrownBootsItem.Boots());
    public static final DeferredItem<Item> GREEN_BOOTS = REGISTRY.register("green_boots", () -> new GreenBootsItem.Boots());
    public static final DeferredItem<Item> PLAINS_HELMET = REGISTRY.register("plains_helmet", () -> new PlainsCamoItem.Helmet());
    public static final DeferredItem<Item> PLAINS_TUNIC = REGISTRY.register("plains_tunic", () -> new PlainsCamoItem.Chestplate());
    public static final DeferredItem<Item> PLAINS_PANTS = REGISTRY.register("plains_pants", () -> new PlainsCamoItem.Leggings());
    public static final DeferredItem<Item> PLAINS_BOOTS = REGISTRY.register("plains_boots", () -> new PlainsCamoItem.Boots());
    public static final DeferredItem<Item> FOREST_HELMET = REGISTRY.register("forest_helmet", () -> new ForestCamoItem.Helmet());
    public static final DeferredItem<Item> FOREST_VEST = REGISTRY.register("forest_vest", () -> new ForestCamoItem.Chestplate());
    public static final DeferredItem<Item> FOREST_PANTS = REGISTRY.register("forest_pants", () -> new ForestCamoItem.Leggings());
    public static final DeferredItem<Item> FOREST_BOOTS = REGISTRY.register("forest_boots", () -> new ForestCamoItem.Boots());
    public static final DeferredItem<Item> TAIGA_HELMET = REGISTRY.register("taiga_helmet", () -> new TaigaCamoItem.Helmet());
    public static final DeferredItem<Item> TAIGA_TUNIC = REGISTRY.register("taiga_tunic", () -> new TaigaCamoItem.Chestplate());
    public static final DeferredItem<Item> TAIGA_PANTS = REGISTRY.register("taiga_pants", () -> new TaigaCamoItem.Leggings());
    public static final DeferredItem<Item> TAIGA_BOOTS = REGISTRY.register("taiga_boots", () -> new TaigaCamoItem.Boots());
    public static final DeferredItem<Item> SAVANNA_HELMET = REGISTRY.register("savanna_helmet", () -> new SavannaCamoItem.Helmet());
    public static final DeferredItem<Item> SAVANNA_TUNIC = REGISTRY.register("savanna_tunic", () -> new SavannaCamoItem.Chestplate());
    public static final DeferredItem<Item> SAVANNA_PANTS = REGISTRY.register("savanna_pants", () -> new SavannaCamoItem.Leggings());
    public static final DeferredItem<Item> SAVANNA_BOOTS = REGISTRY.register("savanna_boots", () -> new SavannaCamoItem.Boots());
    public static final DeferredItem<Item> DESERT_HELMET = REGISTRY.register("desert_helmet", () -> new DesertCamoItem.Helmet());
    public static final DeferredItem<Item> DESERT_TUNIC = REGISTRY.register("desert_tunic", () -> new DesertCamoItem.Chestplate());
    public static final DeferredItem<Item> DESERT_PANTS = REGISTRY.register("desert_pants", () -> new DesertCamoItem.Leggings());
    public static final DeferredItem<Item> DESERT_BOOTS = REGISTRY.register("desert_boots", () -> new DesertCamoItem.Boots());
    public static final DeferredItem<Item> SNOW_HELMET = REGISTRY.register("snow_helmet", () -> new SnowCamoItem.Helmet());
    public static final DeferredItem<Item> SNOW_COAT = REGISTRY.register("snow_coat", () -> new SnowCamoItem.Chestplate());
    public static final DeferredItem<Item> SNOW_PANTS = REGISTRY.register("snow_pants", () -> new SnowCamoItem.Leggings());
    public static final DeferredItem<Item> SNOW_BOOTS = REGISTRY.register("snow_boots", () -> new SnowCamoItem.Boots());
    public static final DeferredItem<Item> WATER_HELMET = REGISTRY.register("water_helmet", () -> new WaterCamoItem.Helmet());
    public static final DeferredItem<Item> WATER_TUNIC = REGISTRY.register("water_tunic", () -> new WaterCamoItem.Chestplate());
    public static final DeferredItem<Item> WATER_PANTS = REGISTRY.register("water_pants", () -> new WaterCamoItem.Leggings());
    public static final DeferredItem<Item> WATER_BOOTS = REGISTRY.register("water_boots", () -> new WaterCamoItem.Boots());
    public static final DeferredItem<Item> MESA_HELMET = REGISTRY.register("mesa_helmet", () -> new MesaCamoItem.Helmet());
    public static final DeferredItem<Item> MESA_TUNIC = REGISTRY.register("mesa_tunic", () -> new MesaCamoItem.Chestplate());
    public static final DeferredItem<Item> MESA_PANTS = REGISTRY.register("mesa_pants", () -> new MesaCamoItem.Leggings());
    public static final DeferredItem<Item> MESA_BOOTS = REGISTRY.register("mesa_boots", () -> new MesaCamoItem.Boots());
    public static final DeferredItem<Item> DIRT_HELMET = REGISTRY.register("dirt_helmet", () -> new DirtCamoItem.Helmet());
    public static final DeferredItem<Item> DIRT_TUNIC = REGISTRY.register("dirt_tunic", () -> new DirtCamoItem.Chestplate());
    public static final DeferredItem<Item> DIRT_PANTS = REGISTRY.register("dirt_pants", () -> new DirtCamoItem.Leggings());
    public static final DeferredItem<Item> DIRT_BOOTS = REGISTRY.register("dirt_boots", () -> new DirtCamoItem.Boots());
    public static final DeferredItem<Item> CLOTH = REGISTRY.register("cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> STURDY_CLOTH = REGISTRY.register("sturdy_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PARACHUTE = REGISTRY.register("parachute", () -> new ParachuteItem());
    public static final DeferredItem<Item> PLAINS_CLOTH = REGISTRY.register("plains_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> FOREST_CLOTH = REGISTRY.register("forest_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TAIGA_CLOTH = REGISTRY.register("taiga_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SAVANNA_CLOTH = REGISTRY.register("savanna_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DESERT_CLOTH = REGISTRY.register("desert_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SNOW_CLOTH = REGISTRY.register("snow_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> WATER_CLOTH = REGISTRY.register("water_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MESA_CLOTH = REGISTRY.register("mesa_cloth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DIRT_CLOTH = REGISTRY.register("dirt_cloth", () -> new Item(new Item.Properties()));
}
